strivial/blueprints/strava_rides.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask import current_app as app

from strivial.services import user_service, athlete_service, activity_service

from datetime import datetime
from dateutil.relativedelta import relativedelta

bp = Blueprint('strava_rides', __name__, url_prefix='/')

@bp.route('/load-rides', methods=['GET'])
def load_rides():
    username = request.remote_addr
    user_has_valid_token = user_service.check_if_user_has_valid_token(username)
    if user_has_valid_token:
        athlete = athlete_service.get_athlete(username)
        # try getting the most recent activity that we have saved for this user
        latest_activity_date = activity_service.get_most_recent_activity_date_for_athlete(athlete.athlete_id)
        # if we don't have one let's just load everything in the last month
        if latest_activity_date is None:
            latest_activity_date = datetime.utcnow() - relativedelta(months=1)
        # add one hour to the time we have, if we are looking at the last month it doesn't matter
        # but if we got the last activity time it prevents us getting that initial activity again
        latest_activity_date += relativedelta(hours=1)

        app.strava.load_activities(start_date=datetime.utcfromtimestamp(latest_activity_date.timestamp()))
        last_five_activities = activity_service.get_last_activities_minimal(5)

        return render_template('pages/main.load.html',
                               logged_in=user_has_valid_token,
                               athlete_name=athlete_service.get_athlete_name(username),
                               last_activities=last_five_activities)
    else:
        return redirect(url_for('home'))

@bp.route('/ride/<activity_id>', methods=['GET'])
def show_ride(activity_id):
    activity = activity_service.get_activity(activity_id)
    return redirect(url_for('home'))

strivial/templates/pages/main.about.html
{% extends 'layouts/main.html' %}
{% block title %}About{% endblock %}
{% block jumbotron %}
<div class="page-header">
  <h1 class="display-3">About</h1>
</div>
<p class="lead">This is just a placeholder page which should be replaced with real content.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tellus ligula, imperdiet id lobortis sit amet, scelerisque non sapien. Duis quis dui quis mauris dapibus fringilla. Pellentesque nec tellus ac diam volutpat malesuada.</p>
<p>In quam arcu, interdum vel arcu viverra, vulputate convallis massa. Sed hendrerit velit a arcu euismod, sit amet consequat lacus imperdiet. Nullam quis dui sapien. Vestibulum placerat, justo non fringilla laoreet, dui ipsum posuere nisi, nec vestibulum eros leo ut sapien.</p>
<p>Vivamus eu felis sed magna scelerisque semper in et libero. Curabitur sed convallis odio, quis venenatis sapien. In convallis a velit ac commodo. Donec sapien ligula, vestibulum ut nisi accumsan, facilisis pretium est. Fusce varius semper orci, et egestas nulla cursus a. Phasellus aliquam, mi ac adipiscing lobortis, ipsum augue aliquam ligula, quis fermentum mi augue vel ligula.</p>
<p>Integer elementum malesuada dolor in aliquet.</p>
{% endblock %}

strivial/templates/pages/main.auth-failed.html
{% extends 'layouts/main.html' %}
{% block title %}Authorization Failed{% endblock %}
{% block jumbotron %}

<div class="page-header">
  <h1 class="display-3">Authorization Failed</h1>
</div>
<p class="lead">Sorry, looks like something went wrong! We can't access your Strava account, if you want to try again you can use the button below.</p>
<p>Error: <strong>{{ error }}</strong></p>
<a class="btn btn-outline-primary btn-lg" role="button" href="{{ auth_url }}">Sign in to Strava &raquo;</a>

{% endblock %}

strivial/templates/pages/main.auth.html
{% extends 'layouts/main.html' %}
{% block title %}Authorized{% endblock %}
{% block jumbotron %}

<div class="page-header">
  <h1 class="display-3">Authorized</h1>
</div>
<p class="lead">You are authorized with Strava as <strong>{{ athlete_name }}</strong>!</p>
<a class="btn btn-outline-primary btn" role="button" href="{{ url_for('strava_rides.load_rides') }}">Load last month of rides</a>

{% endblock %}

strivial/templates/pages/main.home.html
{% extends 'layouts/main.html' %}
{% block title %}Strivial Home{% endblock %}
{% block jumbotron %}

<div class="page-header">
  <h1 class="display-3">Strivial Home</h1>
</div>
<p class="lead">Welcome to Strival!</p>
<a class="btn btn-outline-primary btn-lg" role="button" href="{{ auth_url }}">Sign in to Strava &raquo;</a>

{% endblock %}

strivial/templates/pages/main.load.html
{% extends 'layouts/main.html' %}
{% block title %}Authorized{% endblock %}
{% block jumbotron %}

<div class="page-header">
  <h1 class="display-3">Authorized</h1>
</div>
<p class="lead">You are authorized with Strava as <strong>{{ athlete_name }}</strong>!</p>
<p>Loaded the last month of rides.</p>

{% endblock %}