strivial/blueprints/auth.py
#----------------------------------------------------------------------------#
# Imports
#----------------------------------------------------------------------------#
from strivial.services import user_service, athlete_service, activity_service

from flask import Blueprint, render_template, request, redirect, url_for
from flask import current_app as app

bp = Blueprint('auth', __name__, url_prefix='/')

#----------------------------------------------------------------------------#
# Controllers.
#----------------------------------------------------------------------------#
@bp.route('/')
def home():
    logged_in = user_service.check_if_user_has_valid_token(request.remote_addr)

    if logged_in:
        app.strava.log_in_user_with_active_session(request.remote_addr)
        return show_after_auth()

    return render_template('pages/main.home.html', logged_in=logged_in)

@bp.route('/authorized', methods=['GET', 'POST'])
def authorized():
    error = request.args.get('error')
    if error:
        return render_template('pages/main.auth-failed.html', error=error, logged_in=app.strava.logged_in)

    # Strava sends back something like this:
    #    /authorized?state=&code=xxxxxxxxxxxxxxxxxxxxxxxxxx&scope=read,activity:read
    # the code confirms the Oauth login, the scope gives our access to a user's files
    code = request.args.get('code')
    scope = request.args.get('scope')
    app.strava.log_in_user(request.remote_addr, code, scope)

    return redirect(url_for('home'))

def show_after_auth():
    logged_in = user_service.check_if_user_has_valid_token(request.remote_addr)

    if logged_in:
        athlete_name = athlete_service.get_athlete_name(request.remote_addr)
        #thirty_day_averages = app.strava.get_thirty_day_averages()
        last_five_activities = activity_service.get_last_activities_minimal(5)

    return render_template('pages/main.auth.html', logged_in=logged_in, athlete_name=athlete_name,
                           averages=None, last_activities=last_five_activities)

@bp.route('/logout', methods=['GET', 'POST'])
def logout():
    app.strava.log_out_user(request.remote_addr)

    return redirect(url_for('home'))


@bp.context_processor
def variables():
    return dict(auth_url=app.strava.get_auth_url())

strivial/templates/layouts/main.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/css/jumbotron.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main">

      <!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
        <div class="container">
          {% block jumbotron %}{% endblock %}
        </div>
      </div>

      <div class="container">
        <!-- Example row of columns -->
            <h2>Recent Rides</h2>
            {% if not logged_in %}
            <p>No ride data available when not logged in.</p>
            {% elif last_activities is defined %}
            <div class="row">
              {% for activity in last_activities %}
              <div class="col-8">{{ activity.name }}</div>
              <div class="col">{{ activity.length_in_time|format_seconds }}</div>
              {% endfor %}
            </div>
            <p><a class="btn btn-secondary" href="#" role="button">View all rides &raquo;</a></p>
            {% else %}
            <p>No recent rides found!</p>
            {% endif %}
          </div>
        </div>

        <hr>

      </div> <!-- /container -->

    </main>

    <footer class="container">
      <p><i>Now that's Strivial baby</i></p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>

strivial/templates/layouts/ride.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>{{ ride_name }}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/css/jumbotron.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>

    <main role="main">
    </main>

    <footer class="container">
      <p><i>Now that's Strivial baby</i></p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="/static/js/popper.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
  </body>
</html>